// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jukrqpnrwixqttonsybu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1a3JxcG5yd2l4cXR0b25zeWJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTkyMTEsImV4cCI6MjA2OTk5NTIxMX0.R0VrsxSDRCpKb4fAu_nOMioicjC9gENFMS_NR8hFz8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});